# Generated by Django 4.0.1 on 2022-01-20 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-id']},
        ),
    ]
